### ISSUE TITLE
Can't install citizens

### ISSUE THREAD

**Issue by Arthurmeade12** [exciteabletom/spud#3]
I want to install [Citizens](https://www.spigotmc.org/resources/citizens.13811/), but running
```spud install Citizens```
gives me a plugin called 'Citizens CMD' instead of Citizens. How do I clarify which plugin I want to spud when there is no more text in Citizens' title?
Thanks.

**Comment by exciteabletom** [comment]
Hi Arthur, 

Thanks for getting in touch :)

Unfortunately Spud cannot interact with paid plugins as it is against Spigot's Terms of Service. You will have to install that plugin manually.

You could try using [grifpkg](https://github.com/grifpkg), which has a special agreement with the Spigot owner to break TOS. However it is still in very early stages at the moment and many things are currently broken.

Cheers
